### PR TITLE
Disable jpype by default. Re-enable if it is needed for large vectors ...

### PR DESCRIPTION
**Pull request by markb-onecloudlabs**
… and matrices

### CODE REVIEW

**Comment by markb-onecloudlabs** [comment]
Do not think we need the numpy module in automation, so we should run jpype without it to reduce the number of modules and dependencies we need.

**Comment by onecloud-sean** [comment]
@oc-dimitrik, I gave you write permission to this repo. If this change looks OK to you, can you pull it in?

**Comment by markb-onecloudlabs** [comment]
Thanks will do.

**Comment by markb-onecloudlabs** [comment]
I did a test with this change and a pull from the main repo and it worked as well.

**Comment by oc-dimitrik** [comment]
jpype didn't build by default on bsd, which is why we had to fork. We can check to see if that has been upstream.

This changes looks reasonable to me. Does it speed anything up?

**Comment by markb-onecloudlabs** [comment]
Might speed up local tests since we don't have to install numpy, we had
some issues yesterday with it and i wanted to get away from using it
(numpy) altogether if not needed

On Thu, Oct 8, 2015 at 1:33 PM, Dimitri Kountourogianni <
notifications@github.com> wrote:

> Merged #1 https://github.com/onecloudlabs/jpype/pull/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/onecloudlabs/jpype/pull/1#event-430588284.

## 

Mark Babumoses
Superior Software Engineer in QA
Cell: 617-314-3650
markb@onecloudlabs.com

**Comment by oc-dimitrik** [comment]
Yeah, that's fine. Was wondering if you had actually measured :)

**Comment by oc-dimitrik** [comment]
Also, title is misleading. Should read disable numpy in jpype by default.

**Pull request merged**
